# Generated by Django 2.2 on 2019-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='pictures',
            name='CATEGORY',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='pictures',
            name='IMG_NAME',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='pictures',
            name='IMG_URL',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
