# Generated by Django 2.2.2 on 2019-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190618_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='CARD_COLOR',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
