# Generated by Django 2.2.2 on 2019-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pictures_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='ALL',
            field=models.CharField(default='all', max_length=3),
        ),
    ]
