# Generated by Django 2.2 on 2019-06-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pictures_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='CARD_COLOR',
        ),
    ]
